services:
  client:
    image: swiftly-client:remix
    build: ../client
    ports:
      - "80:3000"
    environment:
      - API_ENDPOINT=http://server:3000
  server:
    image: swiftly-server:express
    build: ../server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@db:5432/postgres
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      PGUSER: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
