# swiftly-client
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: postgres-operator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: swiftly-client:latest
          imagePullPolicy: Never
          env:
            - name: API_ENDPOINT
              value: http://server.postgres-operator.svc.cluster.local:3000
          ports:
            - containerPort: 3000
---
# swiftly-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: postgres-operator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: swiftly-server:latest
          imagePullPolicy: Never
          env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: DB_USER
              valueFrom:
                { secretKeyRef: { name: hippo-pguser-rhino, key: user } }
            - name: DB_PASSWORD
              valueFrom:
                { secretKeyRef: { name: hippo-pguser-rhino, key: password } }
            - name: DB_ADDR
              valueFrom:
                { secretKeyRef: { name: hippo-pguser-rhino, key: host } }
            - name: DB_PORT
              valueFrom:
                { secretKeyRef: { name: hippo-pguser-rhino, key: port } }
            - name: DB_DATABASE
              valueFrom:
                { secretKeyRef: { name: hippo-pguser-rhino, key: dbname } }
            - name: DATABASE_URL
              value: postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_ADDR):$(DB_PORT)/$(DB_DATABASE)?sslmode=require
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: pg-cert
              mountPath: /etc/postgresql/ca.crt
              subPath: ca.crt
      volumes:
        - name: pg-cert
          configMap:
            name: postgres-ca-cert
